#2025-07-18 10:24:20,195 DEBUG [ServerDiag.mastership] manage allarmi:6
#	MapSize 1248 Alarm Size 523 Fri Jul 18 10:24:20 UTC 2025 - 57
#	Manage Degrado Time:0
#	Manage Mastership Time:0
#	Manage All Time:64
#	MASTERSHIP Status:MASTER
#	DEGRADO Status:0
#	DEBUG [ServerDiag.mastership] manage allarmi:7 MapSize 1248 Alarm Size 523 Fri Jul 18 11:22:59 UTC 2025 - 55 Manage Degrado Time:0 Manage Mastership Time:0 Manage All Time:63 MASTERSHIP Status:MASTER DEGRADO Status:0

input {
	beats {
		port => 5044
	}

	tcp {
		port => 50000
	}
}

## Add your filters / logstash plugins configuration here
# patterns_dir => ["./patterns"]
# match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} \[%{DATA:log_source}\] manage allarmi:%{INT:manage_allarmi} %{GREEDYDATA:giulio}" }
# match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} \[%{DATA:log_source}\] manage allarmi:%{INT:manage_allarmi} MapSize %{INT:mapsize} Alarm Size %{INT:alarm_size} %{DATA:giorno} %{DATA:mytimestamp} %{GREEDYDATA:giulio}" }
# match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} \[%{LETTERS_AND_DOT:log_source}\] manage allarmi:%{INT:manage_allarmi} %{GREEDYDATA:giulio}" }
# match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} \[%{LETTERS_AND_DOT:log_source}\] manage %{GREEDYDATA:giulio}" }
# 2025-07-18 13:56:05,689 ERROR [ServerDiag] Eccezione: java.lang.NullPointerException => null
# 2025-07-18 14:02:26,940 DEBUG [profiler.websocket] StateWebSocket instance number -------> 119
# 2025-07-18 14:18:37,557 DEBUG [ServerDiag] UDP client - coda sforata
#
# "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} Eccezione: %{DATA:eccezione}",
# "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} StateWebSocket instance number -------> %{DATA:eccezione}"

filter {

  mutate {
    gsub => [
      "message", "\t", " "
    ]
  }

  # Step 2: Rimuove \r e \n
  mutate {
    gsub => [
      "message", "[\r\n]", ""
    ]
  }

  grok {
    pattern_definitions => {
      "LETTERS_AND_DOT" => "[A-Za-z\.]+"
      "NEXT_MINUS" => "[^-]+"
    }
    match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp} %{DATA:log_level} \[%{LETTERS_AND_DOT:log_source}\] manage allarmi:%{INT:manage_allarmi} MapSize %{INT:mapsize} Alarm Size %{INT:alarm_size} %{LETTERS_AND_DOT:giorno} %{NEXT_MINUS:mytimestamp}- %{INT:durata_manage_allarmi} Manage Degrado Time:%{INT:degrado_time} Manage Mastership Time:%{INT:mastership.time} Manage All Time:%{INT:mastership.all_time} MASTERSHIP Status:%{LETTERS_AND_DOT:mastership.status} DEGRADO Status:%{INT:mastership.degrado}%{GREEDYDATA:giulio}" }

    tag_on_failure => ["_grokparsefailure"]
  }

  mutate {
    convert => {
      "mastership.all_time" => "integer"
    }
    convert => {
      "mastership.degrado" => "integer"
    }
    convert => {
      "mastership.time" => "integer"
    }
    convert => {
      "durata_manage_allarmi" => "integer"
    }
    convert => {
      "degrado_time" => "integer"
    }
  }

  if "_grokparsefailure" in [tags] {
    drop { }
  }

  date {
    match => ["mytimestamp", "MMM dd HH:mm:ss Z yyyy"]
    target => "mytimestamp"
    timezone => "UTC"
  }
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
	}
}

